import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Questrial } from 'next/font/google'

import { Montserrat } from 'next/font/google'


const questrial = Questrial({ 
  subsets: ['latin'],
  weight: "400"
})

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", 
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: "--font-montserrat",
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.className} antialiased`}
      >
      
        {children}

      </body>
    </html>
  );
}
